### ISSUE TITLE
Found a glitch

### ISSUE THREAD

**Issue by lakruzz** [thetechcollective/gh-cpissues#10]
In issue No. 4 in [thetechcollective/dx-intro](https://github.com/thetechcollective/dx-intro/issues/4)

Thos source is this:

<img width="920" alt="image" src="https://github.com/thetechcollective/gh-cpissues/assets/155492/3cf72df8-ebdb-4136-ac4a-3ce64afeecc2">

...but the copy is this:

<img width="988" alt="image" src="https://github.com/thetechcollective/gh-cpissues/assets/155492/9b7f8ea3-6a14-4ff9-aa46-10d533d34187">

There's a corner case that needs to be fixed too

**Comment by Luchassmed** [comment]
Note to [self](https://github.com/outline/rich-markdown-editor/issues/75).

**Comment by lakruzz** [comment]
@Luchassmed I got an idea on how you may be able to solve this issue in a way that doesn't require any awk or regexp at all.

I'm not at my pc today, but give me a call on 20872530 when you read this, then I can share my thoughts and you can the descide yourself which path to take...

_...suspence_. Eh?

**Comment by Luchassmed** [comment]
@lakruzz Checkout the latest commit to debug branch. I have tested the script thoroughly and it seems like it works now. This [stackoverflow post](https://stackoverflow.com/questions/10067266/when-to-wrap-quotes-around-a-shell-variable) suggested to wrap the variable in double quotations... So basically no awk or regex, just double quotations that might have solved the issue 😆
