### ISSUE TITLE
Create unit test

### ISSUE THREAD

**Issue by Luchassmed** [thetechcollective/gh-cpissues#11]
Create unit test for cpissues extension:

- Define setUp: What does the test require or be in a certain state
- Define test suite
- And tearDown  

Maybe take a look at "programming with assertions"

**Comment by Hamsterpants** [comment]
## Useful commands @Luchassmed 
### Build image 
```
docker build -t yourdockername .
```
### Run image with credentials
```
docker run --rm --name yourdockername --env-file credentials.env yourdockername
```
### Execute a script that is in the docker
```
docker exec yourdockername /shutdown.sh
```
### Stop your docker
```
docker stop yourdockername
```

**Comment by Luchassmed** [comment]
[Different testing frameworks](https://github.com/dodie/testing-in-bash/tree/master)
[Make the script a github action to test with already established github actiosn?](https://dev.to/cicirello/how-to-test-a-github-action-with-github-actions-2hag)

**Comment by lakruzz** [comment]
Hi @Hamsterpants and @Luchassmed a few taking points for tomorrow's session

- [ ] It looks like you are sharing this branch - not a bad idea per se, but it builds us to have too much history - let's discuss why this is not always a good approach to have _long-lived branches_ other than main. You need to merge back to main more often.
- [ ] It looks like one of you is committing using the then name "Your name" ([see here](https://github.com/thetechcollective/gh-cpissues/compare/main...11-create-unit-test)) Your git environment is not set up right.
- [ ] In the test folder I see startup (set up?), shut down (tear down?) test (the test suite?) and a master to control it all. You mentioned that you had found a unit test framework - did you skip that?
- [ ] I also see you have credentials and a docker file - cool you are trying to control the environment and make this generic - also looks like some of the things you are trying to achieve would be easier achievable if you tapped into devcontainers
- [ ] In the end you want this to be an automated process, maybe have a workflow (#9) that run your test?
- [ ] I wanted to give it a spin, but I need an instruction - I would usually go into a file named `CONTRIBUTING.md`
- [ ] You are repeatedly using `curl` to access the GitHub API - why aren't you using the `gh cli` your approach does not look like the most obvious choice. (but definitely something a crazy GPT would suggest!)
- [ ] Cool that you [enabled debug mode](https://github.com/thetechcollective/gh-cpissues/blob/bd8cc792968f956d7e2b35a88af4859273fc1a1f/gh-cpissues#L4) consider making this option available _without_ actually creating at new version of the file - the debug mode should be accessible as a configuration (ENV variable or switch) 
- [ ] It's my understanding that you are doing your project management elsewhere; that you set up at Miro board (or something) - you need to come back (home) to GitHub and use the issues and the projects here.

Maybe you have some comments your selv, somthing that you would like to have on the agenda for tomorrow? Throw them here.

**Comment by lakruzz** [comment]
```mermaid
flowchart TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```

**Comment by lakruzz** [comment]
``` mermaid
gitGraph
   commit
   commit
   branch develop
   checkout develop
   commit
   commit
   checkout main
   merge develop
   commit
   commit
 ```

**Comment by lakruzz** [comment]
https://mermaid.js.org/
https://mermaid.live/

**Comment by lakruzz** [comment]
Voltaire:

> _"Perfection is the enemy of good"_

The test is working, still room for improvements but it's working. and the scripts itself is also working - time to merge!

**Comment by Hamsterpants** [comment]
### Test cases:
- Correct number of issues copied
- Successful copy of body
- Issue already exist
- No issues with label
- No label found
- Wrong syntax usage

### Source issues:
- Issues to be copied lives in `gh-issues/issues`
-
